#! /bin/csh -f
#Trevor Cargile
#CS320 - Dr. Carroll
#Assignment 4
#November 18th, 2013

#The tr command is executed first. This deletes all ascii values between 128 an #255.
#The values are 200 and 377 because they are in octal. The -d extension is #the
#extension that is used to "replace" those values with nothing.

#Then the cat command is used. This is a formatting command that can display very 
#helpful things for this program. First, the -v extension displays all ascii values
#as their control characters. The reason I put this second is because it would have
#displayed the other characters if they existed. The only problem is that the -v
#extension doesn't display the newline and the tab. This is why I used the -t and -e.
#They enable the tab and newline to be displayed with their control characters.

#Last is the cut command. Combined with the -c extension the cut command only displays
#the range of characters specified. Since we only need to display the first 72 characters,
#I put the range as 1-72.

#Documentation and Observations:
#Program tested with ~cs320/Data1/input9: Some \\ control characters: ^A^B^C^D^E^F^G^H^I^J^]^^^N^O^V^Z^[$
#Program tested with ~cs320/Data1/input8: two non-ASCII: {}$
#Program tested with ~cs320/Data1/input5: This is a ZERO-line file, since it contains NO newlines!

/usr/local/bin/tr -d '\200-\377' | cat -vte | cut -c 1-72
